select  Sor,PN,Oldal,Tárazás,Darab_p_óra,TervTény, HÉT_R ,HÉT_É,KED_R,KED_É,SZER_R,SZER_É,CSÜ_R,CSÜ_É,PÉN_R,PÉN_É,SZOM_R,SZOM_É,VAS_R,VAS_É
 from
((SELECT terv.id as ID,terv.prod_id as Prod, terv.job as Jobszám, terv.partnumber as PN,stations.name as Sor,
terv.stationid as ST_ID,
CASE WHEN terv.seq = 1 THEN "SMT1" ELSE "SMT2" END as oldal,
terv.seq as SIDE_ID,
terv.qty_p_hour as Darab_p_óra,
'Terv' as TervTény,
SUM(CASE WHEN startdate = @report_date THEN qty_terv ELSE 0 END) / qty_p_hour as HÉT_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 12 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as HÉT_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 24 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as KED_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 36 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as KED_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 48 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as SZER_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 60 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as SZER_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 72 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as CSÜ_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 84 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as CSÜ_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 96 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as PÉN_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 108 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as PÉN_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 120 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as SZOM_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 132 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as SZOM_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 144 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as VAS_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 156 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as VAS_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN qty_terv ELSE 0 END) / qty_p_hour as HÉT_R_2,
(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN (waterfall + 2000) ELSE waterfall END) as waterfallc,
pn_data.Project as Termékcsalád,
terv.comments as Megjegyzés,
terv.startup as Tárazás,
terv.mernoki as Mérnöki,
qty_full
from terv LEFT JOIN stations ON terv.stationid=stations.id LEFT JOIN pn_data ON terv.partnumber=pn_data.PartNumber where terv.active=1 and (qty_terv>0 or qty_teny>0) and startdate>=@report_date and startdate<=DATE_ADD(@report_date, INTERVAL 168 HOUR)  group by terv.prod_id order by terv.id)
UNION
(SELECT terv.id as ID,terv.prod_id as Prod,terv.job as Jobszám, terv.partnumber as PN,stations.name as Sor,
terv.stationid as ST_ID,
CASE WHEN terv.seq = 1 THEN "SMT1" ELSE "SMT2" END as oldal,
terv.seq as SIDE_ID,
terv.qty_p_hour as Darab_p_óra,
'Tény' as TervTény,
SUM(CASE WHEN startdate = @report_date THEN qty_teny ELSE 0 END) / qty_p_hour as HÉT_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 12 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as HÉT_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 24 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as KED_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 36 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as KED_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 48 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as SZER_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 60 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as SZER_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 72 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as CSÜ_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 84 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as CSÜ_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 96 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as PÉN_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 108 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as PÉN_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 120 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as SZOM_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 132 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as SZOM_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 144 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as VAS_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 156 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as VAS_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN qty_teny ELSE 0 END) / qty_p_hour as HÉT_R_2,
(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN (waterfall + 2000) ELSE waterfall END) as waterfallc,
pn_data.Project as Termékcsalád, 
terv.comments as Megjegyzés,
terv.startup as Tárazás,
terv.mernoki as Mérnöki,
qty_full
from terv LEFT JOIN stations ON terv.stationid=stations.id LEFT JOIN pn_data ON terv.partnumber=pn_data.PartNumber where terv.active=1 and (qty_terv>0 or qty_teny>0) and startdate>=@report_date and startdate<=DATE_ADD(@report_date, INTERVAL 168 HOUR) group by terv.prod_id order by terv.id)
) x LEFT JOIN harman_tipusok on x.PN=PN_SMD_Mainboard_PCBA WHERE Sor=@sor
order by Sor, waterfallc, TervTény desc