select Prod,Jobszám,PN,Sor,ST_ID,Oldal,SIDE_ID,Megjegyzés,trim(both ' ' from Termékcsalád) as Termékcsalád,Tárazás,Darab_p_óra,qty_full as Darab,TervTény,HÉT_R,HÉT_É,KED_R,KED_É,SZER_R,SZER_É,CSÜ_R,CSÜ_É,PÉN_R,PÉN_É,SZOM_R,SZOM_É,VAS_R,VAS_É,HÉT_R_2,Mérnöki,harman_tipusok.kisz_szint as OUTLEVEL from
((SELECT tervtest.id as ID,tervtest.prod_id as Prod, tervtest.job as Jobszám, tervtest.partnumber as PN,stations.name as Sor,
tervtest.stationid as ST_ID,
CASE WHEN tervtest.seq = 1 THEN "SMT1" ELSE  "SMT2" END as oldal,
tervtest.seq as SIDE_ID,
tervtest.qty_p_hour as Darab_p_óra,
'Terv' as TervTény,
SUM(CASE WHEN startdate = @report_date THEN qty_terv ELSE 0 END) as HÉT_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 12 HOUR) THEN qty_terv ELSE 0 END) as HÉT_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 24 HOUR) THEN qty_terv ELSE 0 END) as KED_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 36 HOUR) THEN qty_terv ELSE 0 END) as KED_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 48 HOUR) THEN qty_terv ELSE 0 END) as SZER_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 60 HOUR) THEN qty_terv ELSE 0 END) as SZER_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 72 HOUR) THEN qty_terv ELSE 0 END) as CSÜ_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 84 HOUR) THEN qty_terv ELSE 0 END) as CSÜ_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 96 HOUR) THEN qty_terv ELSE 0 END) as PÉN_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 108 HOUR) THEN qty_terv ELSE 0 END) as PÉN_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 120 HOUR) THEN qty_terv ELSE 0 END) as SZOM_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 132 HOUR) THEN qty_terv ELSE 0 END) as SZOM_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 144 HOUR) THEN qty_terv ELSE 0 END) as VAS_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 156 HOUR) THEN qty_terv ELSE 0 END) as VAS_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN qty_terv ELSE 0 END) as HÉT_R_2,
(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN (waterfall + 2000) ELSE waterfall END) as waterfallc,
pn_data.Project as Termékcsalád,
tervtest.comments as Megjegyzés,
tervtest.startup as Tárazás,
tervtest.mernoki as Mérnöki,
qty_full
from tervtest LEFT JOIN stations ON tervtest.stationid=stations.id LEFT JOIN pn_data ON tervtest.partnumber=pn_data.PartNumber where tervtest.active=1 and (qty_terv>0 or qty_teny>0) and startdate>=@report_date and startdate<=DATE_ADD(@report_date, INTERVAL 168 HOUR)  group by tervtest.prod_id order by tervtest.id)
UNION
(SELECT tervtest.id as ID,tervtest.prod_id as Prod,tervtest.job as Jobszám, tervtest.partnumber as PN,stations.name as Sor,
tervtest.stationid as ST_ID,
CASE WHEN tervtest.seq = 1 THEN "SMT1" ELSE "SMT2" END as oldal,
tervtest.seq as SIDE_ID,
tervtest.qty_p_hour as Darab_p_óra,
'Tény' as TervTény,
SUM(CASE WHEN startdate = @report_date THEN qty_teny ELSE 0 END) as HÉT_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 12 HOUR) THEN qty_teny ELSE 0 END) as HÉT_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 24 HOUR) THEN qty_teny ELSE 0 END) as KED_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 36 HOUR) THEN qty_teny ELSE 0 END) as KED_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 48 HOUR) THEN qty_teny ELSE 0 END) as SZER_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 60 HOUR) THEN qty_teny ELSE 0 END) as SZER_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 72 HOUR) THEN qty_teny ELSE 0 END) as CSÜ_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 84 HOUR) THEN qty_teny ELSE 0 END) as CSÜ_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 96 HOUR) THEN qty_teny ELSE 0 END) as PÉN_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 108 HOUR) THEN qty_teny ELSE 0 END) as PÉN_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 120 HOUR) THEN qty_teny ELSE 0 END) as SZOM_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 132 HOUR) THEN qty_teny ELSE 0 END) as SZOM_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 144 HOUR) THEN qty_teny ELSE 0 END) as VAS_R,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 156 HOUR) THEN qty_teny ELSE 0 END) as VAS_É,
SUM(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN qty_teny ELSE 0 END) as HÉT_R_2,
(CASE WHEN startdate = DATE_ADD(@report_date, INTERVAL 168 HOUR) THEN (waterfall + 2000) ELSE waterfall END) as waterfallc,
pn_data.Project as Termékcsalád, 
tervtest.comments as Megjegyzés,
tervtest.startup as Tárazás,
tervtest.mernoki as Mérnöki,
qty_full
from tervtest LEFT JOIN stations ON tervtest.stationid=stations.id LEFT JOIN pn_data ON tervtest.partnumber=pn_data.PartNumber where tervtest.active=1 and (qty_terv>0 or qty_teny>0) and startdate>=@report_date and startdate<=DATE_ADD(@report_date, INTERVAL 168 HOUR) group by tervtest.prod_id order by tervtest.id)
) x LEFT JOIN harman_tipusok on x.PN=PN_SMD_Mainboard_PCBA WHERE Sor=@sor
order by Sor, waterfallc, TervTény desc